### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Scanix** [forwards-long-jump/spark-pudding#1]
I propose this one : https://fr.wikipedia.org/wiki/Beerware

**Comment by Blatoy** [comment]
I'm not against it as long as it works like the MIT license, which seems to not exactly be the case
https://romanrm.net/beerware
https://securityboulevard.com/2019/09/lets-talk-licenses-beware-the-beerware-license/

We could just add the beer statement in the MIT license file though :eyes:

**Comment by Scanix** [comment]
Boah I think that it would be a nice "joke" but a good old MIT license will do the job.
